title: Jorge Luis Vargas Barrera # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ML engineer with 1.5+ years of experience in machine learning, neural networks and a master´s degree in Computational Statistics.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jorgelvb0/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
